### ISSUE TITLE
自增的主键，如果是bigint，tag没有自动设置为autoincr

### ISSUE THREAD

**Issue by hsyan2008** [go-xorm/cmd#11]
如果是int，生成的如下
Id        int       `xorm:"not null pk autoincr INT(11)"`
如果是bigint，生成如下
Id         int64     `xorm:"BIGINT(20)"`
以上两者都是AUTO_INCREMENT的无符号的自增主键

**Comment by lunny** [comment]
如果是Id并且类型是int64，则自动为pk和autoincr。请查看文档。http://xorm.io/docs

**Comment by hsyan2008** [comment]
既然不是issue，那我先关了，有问题再开
