### ISSUE TITLE
 [Error] reverse.go:172 sql: unknown driver "sqlite3" (forgotten import?)

### ISSUE THREAD

**Issue by qq277049** [go-xorm/cmd#32]
devdeMacBook-Pro:autoBet dev$ xorm reverse sqlite3  ./autoBetDb.db /Users/dev/go/src/github.com/go-xorm/cmd/xorm/templates/goxorm
2018/03/27 16:51:12 [Error] reverse.go:172 sql: unknown driver "sqlite3" (forgotten import?)

**Comment by ziqiangcheng** [comment]
you need to "go build -tags sqlite3" to build "xorm" first.
1. cd to %GOPATH%/src/github.com/go-xorm/cmd/xorm
2. run "go build -tags sqlite3"
3. a new "xorm" will be generated at current dir
4. copy the new "xorm" to %GOPATH%/bin
5. run your "xorm reverse ..." again. Done!
