### ISSUE TITLE
怎么折腾都是这样，爬墙和不爬墙都是这个结果

### ISSUE THREAD

**Issue by neatstudio** [go-xorm/cmd#42]
go get github.com/go-xorm/cmd/xorm
package cloud.google.com/go/civil: unrecognized import path "cloud.google.com/go/civil" (https fetch: Get https://cloud.google.com/go/civil?go-get=1: dial tcp 216.58.199.110:443: i/o timeout)

**Comment by neatstudio** [comment]
其实主要可能是因为 https://cloud.google.com/go/civil?go-get=1，这个页面有一个redirect的跳转。导致我下载不下来。

我的go get 使用了proxifier进行托管。当使用go get 的时候，就会默认爬梯子了。

**Comment by BetaCat0** [comment]
好的，那现在问题解决了吗 @neatstudio

**Comment by neatstudio** [comment]
![image](https://user-images.githubusercontent.com/229186/45722491-37055e80-bbdf-11e8-88c8-a1c3e82028a6.png)
重写 Proxifier 的规则 ，target host中加入了：cloud.google.com ; golang.com 等，反正哪个出错加哪个。现在终于好了！
象这种工具型的，应该出几个release的版本。大不了就直接download用了（只要放在指定的目录下，在文档里加上就行）

**Comment by BetaCat0** [comment]
Congratulations ！😄
