### ISSUE TITLE
xorm reverse 

### ISSUE THREAD

**Issue by Aload** [go-xorm/cmd#47]
这我就不是很懂了 ，我把密码改成这样就没事了 1701&CahE ->111

D:\coding\go_code\SmartMigrate\src\github.com\go-xorm\cmd\xorm>xorm reverse mysql zhyb:1701&CahE@(192.168.29.194:3306)/iebm_platform_v2_db_dev?charset=utf8  D:/coding/go_code/SmartMigrate/src/tmp
params error, please see xorm help reverse
'CahE@' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\coding\go_code\SmartMigrate\src\github.com\go-xorm\cmd\xorm>xorm reverse mysql zhyb:11@(192.168.29.194:3306)/iebm_platform_v2_db_dev?charset=utf8  D:/coding/go_code/SmartMigrate/src/tmp
2018/12/22 12:15:20 [Error] reverse.go:178 Error 1045: Access denied for user 'zhyb'@'192.168.29.158' (using password: YES)

**Comment by solarhell** [comment]
`fmt.Sprintf` escape 下就好了
