### ISSUE TITLE
reverse example 有问题？

### ISSUE THREAD

**Issue by YogurtShen** [go-xorm/cmd#5]
<code>xorm reverse mysql root:@/xorm_test?charset=utf8 templates/goxorm</code>
这个example跑不通？会报<code>no matches found</code>的错误
去掉<code>charset=utf8</code>竟然就跑通了……

**Comment by YogurtShen** [comment]
还有一个，按照go-sql-driver/mysql官方教程写法连接remote host时
<code>username:password@tcp(xxx.mysql.rds.aliyuncs.com:3306)/xxx_test</code>
自己写段小程序证明是能连接并操作的
但是这个地址放到reverse中又会报<code>no matches found</code>的错误？

**Comment by lunny** [comment]
得测试下。

**Comment by xigang** [comment]
~~~
➜  xorm git:(master) xorm reverse mysql root:wangxigang@tcp(127.0.0.1:3306)/test?charset=utf8 templates/goxorm ./test
zsh: no matches found: root:wangxigang@tcp(127.0.0.1:3306)/test?charset=utf8
~~~

我使用xorm reverse command也是报这个错误？不知道是什么原因？

**Comment by baoyangc** [comment]
一样的问题

**Comment by dawniii** [comment]
解决办法：
1. root:@/xorm_test?charset=utf8 这部分用双引号包起来
2. templates/goxorm  这个目录写绝对路径或者copy到当前目录
