### ISSUE TITLE
go get 请求不到cloud.google.com怎么办

### ISSUE THREAD

**Issue by baselin** [go-xorm/cmd#59]
Fetching https://cloud.google.com/go/civil?go-get=1
https fetch failed: Get https://cloud.google.com/go/civil?go-get=1: dial tcp 216.58.200.238:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
package cloud.google.com/go/civil: unrecognized import path "cloud.google.com/go/civil" (https fetch: Get https://cloud.google.com/go/civil?go-get=1: dial tcp 216.58.200.238:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

**Comment by BetaCat0** [comment]
代理工具配置的对吗

**Comment by baselin** [comment]
配置了就是只是这个网站连不上，你们用的啥工具？

**Comment by baselin** [comment]
> 代理工具配置的对吗



> 代理工具配置的对吗

配置了就是只是这个网站连不上，你们用的啥工具？

**Comment by baselin** [comment]
配置了就是只是这个网站连不上，你们用的啥工具？

**Comment by BetaCat0** [comment]
代理的话如果使用的是 ss 或者 ssr，
Windows cmd:
```
set http_proxy=xxxxxxxx
set https_proxy=xxxxxxxx
```
Bash:
```
export http_proxy=xxxxxxxx
export https_proxy=xxxxxxxx
```
v2ray流程同上，地址为本地设置的**http** host+代理端口；

**Comment by baselin** [comment]
> 代理的话如果使用的是 ss 或者 ssr，
> Windows cmd:
> 
> ```
> set http_proxy=xxxxxxxx
> set https_proxy=xxxxxxxx
> ```
> Bash:
> 
> ```
> export http_proxy=xxxxxxxx
> export https_proxy=xxxxxxxx
> ```
> v2ray流程`Bash`，地址为本地设置的**http** host+代理端口；

对的是这样的，找到原因了，代理背墙了

**Comment by BetaCat0** [comment]
@baselin 好的😂
