### ISSUE TITLE
请问reverse操作时如何去掉公共前缀

### ISSUE THREAD

**Issue by YogurtShen** [go-xorm/cmd#6]
因为数据库里的表都有公共前缀xxx_
这样直接reverse成go struct时就都带了XXX，想全部去掉
请问该如何做呢？

**Comment by lunny** [comment]
目前尚不支持此功能。

**Comment by admpub** [comment]
@YogurtShen 将 https://github.com/go-xorm/cmd/blob/master/xorm/templates/goxorm/config 文件中`prefix`的值改为你自己的前缀名称就可以了

**Comment by lunny** [comment]
啊。什么时候实现的？我都忘记了。

**Comment by scholar-ink** [comment]
@admpub 我在config里面加了prefix  但是在xorm 执行sql的 时候没有把这个prefix 自动加到tableName前面
